# api
FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install
ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
RUN npx prisma generate

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]