# Imagen base de node
FROM node:20-alpine

# Crear el directorio de trabajo
WORKDIR /frontend

# Copia los archivos de configuración del npm
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copia el código
COPY . .

# Expone el puerto donde corre Vite
EXPOSE 5173

# Comando para ejecutar el proyecto
CMD ["npm", "run", "dev", "--", "--host"]